config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :services, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :registres, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :appoints, only: [:index, :show, :new, :create, :edit, :update, :destroy]



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appoint.rb
class Appoint < ApplicationRecord
  has_many :registres
  has_many :users, through: :registres

  validates :title, presence: true
  validates :description, presence: true
  validates :horaire, presence: true
end

app/models/registre.rb
class Registre < ApplicationRecord
  belongs_to :user
  belongs_to :appoint
  belongs_to :service
  validates :user_id, presence: true
  validates :appoint_id, presence: true
  validates :service_id, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :users
  has_many :registres
  has_many :services, through: :registres
  validates :name, presence: true
  validates :description, presence: true
  validates :time, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appoints, through: :registres
  has_many :registres
  has_many :services, through: :registres



  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :civility, presence: true
  validates :phone, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    role == 'admin'
  end

  def user?
    role == 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/appoints_controller.rb
class AppointsController < ApplicationController
  before_action :set_appoint, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create]

  def index
    @appoints = Appoint.all
  end

  def show
  end

  def new
    @appoint = Appoint.new
  end

  def create
    @appoint = Appoint.new(appoint_params)
    if @appoint.save
      redirect_to appoints_path(@appoint)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @appoint.destroy
    redirect_to appoints_path
  end

  def edit
  end

  def update
    if @appoint.update(appoint_params)
      redirect_to @appoint
    else
      render :edit
    end
  end

  private

  def appoint_params
    params.require(:appoint).permit(:title, :description, :horaire)
  end

  def set_appoint
    @appoint = Appoint.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/registres_controller.rb
class RegistresController < ApplicationController
  before_action :set_registrer, only: [:show, :edit, :update, :destroy]
  before_action :set_appoint, only: [:new, :create, :show]
  def index
    @appoints = Appoint.all
    @registres = Registre.all
  end

  def show
  end

  def new
    @registre = Registre.new
  end

  def create
    @registre = Registre.new(registre_params)
    @registre.user = current_user
    @registre.appoint = @appoint
    if @registre.save
      redirect_to @appoints
    else
      render :new
    end
  end

  def edit
  end

  def update
    @registre.update(registre_params)
    redirect_to @registre
  end

  def destroy
    @registre.destroy
    redirect_to appoints_path
  end

  private

  def registre_params
    params.require(:registre).permit(:user_id, :appoint_id)
  end

  def set_registrer
    @registre = Registre.find(params[:id])
  end

  def set_appoint
    @appoint = Appoint.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to services_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path
  end

  private

  def service_params
    params.require(:service).permit(:name, :description, :time, :price)
  end

  def set_service
    @service = Service.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appoints/create.html.erb
<h1>Appoints#create</h1>
<p>Find me in app/views/appoints/create.html.erb</p>

app/views/appoints/destroy.html.erb
<h1>Appoints#destroy</h1>
<p>Find me in app/views/appoints/destroy.html.erb</p>

app/views/appoints/edit.html.erb
<h1>Appoints#edit</h1>
<p>Find me in app/views/appoints/edit.html.erb</p>

app/views/appoints/index.html.erb
<h1>Appoints#index</h1>
<p>Find me in app/views/appoints/index.html.erb</p>

<% @appoints.each do |appoint| %>
  <div class="card">

      <h5><%= appoint.title %></h5>
      <p><%= appoint.description %></p>
      <p><%= appoint.horaire %></p>

<%= link_to 'voir le détail', appoint  %>
<% end %>
  </div>

  <%= link_to 'Prendre rendez-vous', new_appoint_path %>

app/views/appoints/new.html.erb
<h1>Appoints#new</h1>
<p>Find me in app/views/appoints/new.html.erb</p>

<%= simple_form_for @appoint do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>

  <%= f.input :horaire, as: :date  %>

  <%= f.input :horaire, as: :time  %>
  <%= f.submit %>
<% end %>
<%= link_to "Retournez à vos reservation", appoints_path  %>

app/views/appoints/show.html.erb
<h1>Appoints#show</h1>
<p>Find me in app/views/appoints/show.html.erb</p>

<%= @appoint.title %>
<%= @appoint.description %>
<%= @appoint.horaire %>

<%= link_to 'Retournez à vos reservation', appoints_path  %>

<%= link_to 'Modifier mon rendez-vous', edit_appoint_path(@appoint) %>

<%= link_to "delete", appoint_path(@appoint), data: { turbo_method: :delete}%>

app/views/appoints/update.html.erb
<h1>Appoints#update</h1>
<p>Find me in app/views/appoints/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MCAFtrue</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>



  <body>
<%= render 'shared/navbar' %>
    <%= yield %>
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/registres/create.html.erb
<h1>Registres#create</h1>
<p>Find me in app/views/registres/create.html.erb</p>

app/views/registres/destroy.html.erb
<h1>Registres#destroy</h1>
<p>Find me in app/views/registres/destroy.html.erb</p>

app/views/registres/edit.html.erb
<h1>Registres#edit</h1>
<p>Find me in app/views/registres/edit.html.erb</p>

app/views/registres/index.html.erb
<h1>Registres#index</h1>
<p>Find me in app/views/registres/index.html.erb</p>

    

app/views/registres/new.html.erb
<h1>Registres#new</h1>
<p>Find me in app/views/registres/new.html.erb</p>

app/views/registres/show.html.erb
<h1>Registres#show</h1>
<p>Find me in app/views/registres/show.html.erb</p>

app/views/registres/update.html.erb
<h1>Registres#update</h1>
<p>Find me in app/views/registres/update.html.erb</p>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/destroy.html.erb
<h1>Services#destroy</h1>
<p>Find me in app/views/services/destroy.html.erb</p>

app/views/services/edit.html.erb
<h1>Services#edit</h1>
<p>Find me in app/views/services/edit.html.erb</p>

app/views/services/index.html.erb
<h1>Nos services</h1>
<div><%= link_to 'New Service', new_service_path, :class=>"btn btn-primary" %>
</div>

<div>
<% @services.each do |service| %>
  <div class="card">

      <h5><%= service.name %></h5>
      <p><%= service.time %></p>
<%= link_to 'voir le détail', service  %>
    <% end %>
  </div>
</div>

app/views/services/new.html.erb
<h1>Services#new</h1>
<p>Find me in app/views/services/new.html.erb</p>
<%= simple_form_for @service do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :time %>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/services/show.html.erb
<h1>Services#show</h1>
<p>Find me in app/views/services/show.html.erb</p>
  <div class="card">
    <%= link_to 'modifier un service',edit_service_path  %>


      <h5><%= @service.name %></h5>
      <p><%= @service.description %></p>
      <p><%= @service.time %></p>
      <p><%= @service.price %></p>
      <%= link_to "delete", service_path(@service), data: { turbo_method: :delete}%>

  </div>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_form_new_appoint.html.erb
<% simple_form_for @appoints do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :start_at, as: :datetime  %>
  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
          <%= link_to "Accueil", "/", class: "nav-link" %>
          </li>

          <li class="nav-item active">
          <%= link_to "Prendre rendez-vous", appoints_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Services", services_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <% if current_user %>
              <%= link_to "Profil", registres_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              <%= link_to "Another action", "", class: "dropdown-item" %>
            <% else %>
            <%= link_to "Créé un compte", new_user_registration_path %>
            <%= link_to "Se connecter", new_user_session_path %>
            <% end %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>